version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /usr/local/var/run
    volumes:
      - webroot-data:/var/www/html/data
    healthcheck:
      test: ["CMD", "php", "-m"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
    ports:
      - "8080:80"
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/log/nginx
      - /tmp
    volumes:
      - webroot-data:/var/www/html/data:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost/ >/dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  webroot-data:
