version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./webroot:/var/www/html:rw,cached
      - ./config/php:/usr/local/etc/php/conf.d:ro
      - ./webroot/data:/var/www/html/data
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=20000
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256
    healthcheck:
      test: ["CMD", "php", "-m"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./webroot:/var/www/html:ro
      - ./webroot/data:/var/www/html/data:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost/ >/dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 3
